try{
    globalThis.c = new AudioContext();
} catch{
    document.body.innerHTML += "<h1 id='er' class='e'>Sorry, this browser is not for you :(</h1>";
    document.body.innerHTML += "<img id='notAllowed' class='e' src='imgs/NotAllowed.png' width=250>";
    document.body.innerHTML += 
    `
    <p style='class='e' id='reason''>Why this browser is not for you?<br>Because this browser is doesn't support
    <strong>AudioContext</strong> in JavaScript<br>Or your browser is not updated (old version)</p>`;

    throw "[Program Stopped]";
}


function playHertz(fre, forSecs){
    const o = c.createOscillator();
    o.type = "square";
    o.frequency.value = fre;
    o.connect(c.destination);
    o.start();
    o.stop(c.currentTime + forSecs);
}


window.addEventListener("keydown", (e) => {
    if(running) return;
    if(!(e.code === "Backspace")) return;
    if(!confirm("Are you sure to reset your High Score?")) return;

    localStorage.clear();
});

const radius = 6.1;

function isTouching(el1, el2) {
    // [i] This function was 98% generated by Microsoft Copilot

    const rect1 = el1.getBoundingClientRect();
    const rect2 = el2.getBoundingClientRect();

    return !(
    rect1.right - radius < rect2.left + radius || 
    rect1.left - radius > rect2.right + radius || 
    rect1.bottom - radius< rect2.top + radius || 
    rect1.top - radius > rect2.bottom + radius
    );
}

let running = false;

document.body.innerHTML += `<div id='container' class='e'>
    <button id='start' class='e'>Start</button>
</div>`;

const container = document.getElementById("container");
const start = document.getElementById("start");

const score = document.createElement("div");

if(localStorage.getItem("HI") === null){
    localStorage.setItem("HI", 0);
}
let Score = 0;

score.id = "score";
score.classList = "e";
container.appendChild(score);

start.onclick = () => {

Score = 0;

try{
    for(let bh of clones){
        container.removeChild(bh);
        clones = [];
    }

    container.removeChild(star);
} catch(E){
    console.clear();
}

try{
    gameOver_.hidden = true;
} catch{
    console.clear();
}

start.hidden = true;
const star = document.createElement("img");
star.src = "imgs/Star.png";
star.id = "star";
star.classList = "e";
container.appendChild(star);

let jump = false;

window.addEventListener("keydown", (e) => {
    if(!running) return;

    if(!(e.code === "Space")) return;
    if(jump) return;

    jump = true;

    playHertz(261, 0.05);

    star.style.animation = "";
    setTimeout(() => star.style.animation = "jump 0.78s");

    setTimeout(() => {
        jump = false;
    }, 750);
});

container.addEventListener("mousedown", () => {
    if(!running) return;

    if(jump) return;

    jump = true;

    playHertz(261, 0.05);

    star.style.animation = "";
    setTimeout(() => star.style.animation = "jump 0.78s");

    setTimeout(() => {
        jump = false;
    }, 750);
});

globalThis.clones = [];
let x = 95;

for(let i=0; i<3; i++){
    const bh = document.createElement("img");
    bh.width = 50;
    bh.src = "imgs/blackHole.png";

    bh.classList = "e";
    bh.style.position = "absolute";
    bh.style.top = "85%";
    bh.style.left = `${x}%`;
    bh.xPos = x;

    x -= 28;

    container.appendChild(bh);
    clones[clones.length] = bh;

}

function gameOver(){
    gameOver_.hidden = false;

    playHertz(30, 0.6);
}


let speed = 0.7

function mainloop(){
    running = true;
    for(let bh of clones){
        bh.xPos -= speed;
        bh.style.left = `${bh.xPos}%`

        if(bh.xPos <= 5){
            bh.xPos = 90;
            bh.style.left = bh.xPos;
        }

        if(isTouching(star, bh)){
        running = false;
        }

        
    }

    if((devicePixelRatio !== 1.5) || (devicePixelRatio !== 1.75) || (devicePixelRatio !== 1)){running = false;}

    if(!running){
        gameOver();
    } else{
        setTimeout(mainloop, 20);
    }


    Score += 1;

    if(Score > localStorage.getItem("HI")){
        localStorage.setItem("HI", Score);
    }

    score.innerText = `HI: ${localStorage.getItem("HI")}   ${Score}`;

    speed += 0.000003;
}

mainloop();

};

const gameOver_ = document.createElement("h1");
gameOver_.hidden = true;
gameOver_.innerText = "Game Over, Click here to start again";
gameOver_.id = "gameOver";
gameOver_.classList = "e";
gameOver_.onclick = start.onclick;

container.appendChild(gameOver_);


